server.port=8083

spring.application.name=RopaStoreValidation

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=Dev2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
